// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhhzWSC4cECL0vNkM6FABHvzz3DqRMN2E',
    appId: '1:423896652835:web:d112b4dbc9f75483b9a596',
    messagingSenderId: '423896652835',
    projectId: 'sorttasks',
    authDomain: 'sorttasks.firebaseapp.com',
    storageBucket: 'sorttasks.appspot.com',
    measurementId: 'G-EY9RGQFRH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVURrDGRUby6eIhKdH_34OnTCpsuOTK7A',
    appId: '1:423896652835:android:5b4a0e8e45ad725eb9a596',
    messagingSenderId: '423896652835',
    projectId: 'sorttasks',
    storageBucket: 'sorttasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Att8gcRcjdfUAkz8a3jD2w8jadmTPiQ',
    appId: '1:423896652835:ios:c9ceebf7b0bf0ab4b9a596',
    messagingSenderId: '423896652835',
    projectId: 'sorttasks',
    storageBucket: 'sorttasks.appspot.com',
    iosBundleId: 'com.example.sorttasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Att8gcRcjdfUAkz8a3jD2w8jadmTPiQ',
    appId: '1:423896652835:ios:cdc5f193b6ce3ceab9a596',
    messagingSenderId: '423896652835',
    projectId: 'sorttasks',
    storageBucket: 'sorttasks.appspot.com',
    iosBundleId: 'com.example.sorttasks.RunnerTests',
  );
}
